### ISSUE TITLE
getting intermittent Readme API error:  The endpoint you called (GET /v1/docs) doesn't exist

### ISSUE THREAD

**Issue by fscelliott** [flowcommerce/readme-sync#36]
I'm using readme-sync to publish these docs: 
https://github.com/sensible-hq/sensible-docs

About 2 weeks ago I started getting the error in the issue title.  for example on [this readme-sync action run](https://github.com/sensible-hq/sensible-docs/actions/runs/4137576330/jobs/7152918746#step:6:129).

1st known instance of this happening  was feb 9 2023. I haven't edited my GH actions (including [readme-sync](https://github.com/sensible-hq/sensible-docs/blob/main/.github/workflows/sync_guides_readme%20.yml) in months, nor my categories for my docs.

this was the first commit to fail:
https://github.com/sensible-hq/sensible-docs/commit/b0da28eb7e073ebd2cd401581acad44efef92c5b

**Comment by fscelliott** [comment]
The issue is intermittent.

for example, after I started getting the error, there was 1 day when the error disappeared:

last failed run:
https://github.com/sensible-hq/sensible-docs/actions/runs/4245735233

first success:
https://github.com/sensible-hq/sensible-docs/actions/runs/4245735233

( string of success runs)

last success :
https://github.com/sensible-hq/sensible-docs/actions/runs/4255832837

first fail:
https://github.com/sensible-hq/sensible-docs/actions/runs/4256089175

It seems as if the last two times the errors started, it started with a commit in which I created a new topic.

**Comment by benwaffle** [comment]
This is pretty weird. It's doing a POST request, so why is the error about GET? I don't see any weird network stuff in your github actions workflow. Have you tried contacting readme.com support about this? Maybe they've seen it before.

**Comment by fscelliott** [comment]
It hasn't happened in a long time, so i'm closing it.
